[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

# Compiler settings
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
sepolia = "https://1rpc.io/sepolia"
mainnet = "https://eth.drpc.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
